### ISSUE TITLE
Error when using json-reporter

### ISSUE THREAD

**Issue by vpatton** [holidaycheck/gemini-json-reporter#1]
Latest version of node and gemini

Critical error:
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /Users/van.patton/test-framework-gemini/node_modules/gemini/lib/plugins.js:18:32
    at arrayEach (/Users/van.patton/test-framework-gemini/node_modules/gemini/node_modules/lodash/lodash.js:530:11)
    at Function.forEach (/Users/van.patton/test-framework-gemini/node_modules/gemini/node_modules/lodash/lodash.js:9319:14)
    at LodashWrapper.object.(anonymous function) [as forEach] (/Users/van.patton/test-framework-gemini/node_modules/gemini/node_modules/lodash/lodash.js:15626:25)
    at Object.module.exports.load._.map.reject.map.forEach [as load] (/Users/van.patton/test-framework-gemini/node_modules/gemini/lib/plugins.js:18:12)
    at Gemini._loadPlugins (/Users/van.patton/test-framework-gemini/node_modules/gemini/lib/gemini.js:97:30)
    at new Gemini (/Users/van.patton/test-framework-gemini/node_modules/gemini/lib/gemini.js:38:14)
    at /Users/van.patton/test-framework-gemini/node_modules/gemini/lib/cli/index.js:89:16
    at tryCatcher (/Users/van.patton/test-framework-gemini/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/van.patton/test-framework-gemini/node_modules/bluebird/js/release/method.js:39:29)
    at runGemini (/Users/van.patton/test-framework-gemini/node_modules/gemini/lib/cli/index.js:87:23)
    at Command.<anonymous> (/Users/van.patton/test-framework-gemini/node_modules/gemini/lib/cli/index.js:33:37)
    at Command.listener (/Users/van.patton/test-framework-gemini/node_modules/gemini/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)

**Comment by lo1tuma** [comment]
Hi @vpatton, thanks for the issue. Are you sure that you are using the latest version of gemini? Because in the latest version the file `gemini/lib/plugins.js` doesn’t exist anymore, but the stacktrace you posted points to this file.

I’ve executed the tests with node v6 and v7 and wasn’t able to reproduce this problem. What node version do you use exactly? Are you sure this plugin causes the problem or do you use any other gemini plugins? When does this problem happen exactly?

**Comment by vpatton** [comment]
Ok so after reinstalling node v6.9 and reinstalling all the packages it's working again, not sure what happened thx
